import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AddButton from "@/components/addButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <nav>
            <div className="flex flex-row justify-between p-10">
              <div>
                <Link href={'/'}>
                  <h3 className="font-bold text-xl">School</h3>
                </Link>
              </div>
              <div>
                <ul className="flex flex-row list-none text-fuchsia-400 ">
                  <li>
                    <AddButton />
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        {children}
      </body>
    </html>
  );
}
